# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Regime Shifts in Holocene Paleohydrology as Recorded by Asian Speleothems
author: Alexander James
logo: logo.pdf
copyright: "2025"
only_build_toc_files: true
execute:
  execute_notebooks: force
  timeout: 3600

latex:
  latex_documents:
    targetname: book.tex

repository:
  url: https://github.com/alexkjames/AsianSpeleothemCoherency
  branch: main

html:
  use_issues_button: true
  use_repository_button: true
  announcement: ""

launch_buttons:
  notebook_interface: "jupyterlab"
  binderhub_url: ""